// Mocks generated by Mockito 5.4.6 from annotations
// in studio_pair_backend/test/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:jaguar_jwt/jaguar_jwt.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:studio_pair_backend/src/modules/auth/auth_repository.dart'
    as _i2;
import 'package:studio_pair_backend/src/services/notification_service.dart'
    as _i7;
import 'package:studio_pair_backend/src/utils/jwt_utils.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  @override
  _i3.Future<Map<String, dynamic>> createUser({
    required String? id,
    required String? email,
    required String? passwordHash,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [], {
              #id: id,
              #email: email,
              #passwordHash: passwordHash,
              #displayName: displayName,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>?> findByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#findByEmail, [email]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<bool> emailExists(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#emailExists, [email]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> updatePassword(String? userId, String? passwordHash) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [userId, passwordHash]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> incrementFailedLoginAttempts(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementFailedLoginAttempts, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resetFailedLoginAttempts(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#resetFailedLoginAttempts, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> softDeleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteUser, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> store2FASecret(String? userId, String? secret) =>
      (super.noSuchMethod(
            Invocation.method(#store2FASecret, [userId, secret]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> enable2FA(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#enable2FA, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> disable2FA(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#disable2FA, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> storeBackupCodes(
    String? userId,
    List<String>? hashedCodes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#storeBackupCodes, [userId, hashedCodes]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> useBackupCode(String? userId, String? codeHash) =>
      (super.noSuchMethod(
            Invocation.method(#useBackupCode, [userId, codeHash]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>> createSession({
    required String? id,
    required String? userId,
    required String? refreshTokenHash,
    required String? ipAddress,
    required String? userAgent,
    required DateTime? expiresAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [], {
              #id: id,
              #userId: userId,
              #refreshTokenHash: refreshTokenHash,
              #ipAddress: ipAddress,
              #userAgent: userAgent,
              #expiresAt: expiresAt,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>?> findSessionByRefreshToken(
    String? refreshTokenHash,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findSessionByRefreshToken, [refreshTokenHash]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> listSessions(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#listSessions, [userId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<bool> revokeSession(String? sessionId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#revokeSession, [sessionId, userId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> revokeAllSessions(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#revokeAllSessions, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSessionRefreshToken(
    String? sessionId,
    String? newRefreshTokenHash,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSessionRefreshToken, [
              sessionId,
              newRefreshTokenHash,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> createPasswordResetToken({
    required String? userId,
    required String? tokenHash,
    required DateTime? expiresAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPasswordResetToken, [], {
              #userId: userId,
              #tokenHash: tokenHash,
              #expiresAt: expiresAt,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> findPasswordResetToken(String? tokenHash) =>
      (super.noSuchMethod(
            Invocation.method(#findPasswordResetToken, [tokenHash]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> markPasswordResetTokenUsed(String? tokenHash) =>
      (super.noSuchMethod(
            Invocation.method(#markPasswordResetTokenUsed, [tokenHash]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [JwtUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockJwtUtils extends _i1.Mock implements _i4.JwtUtils {
  @override
  String generateAccessToken(String? userId, String? email) =>
      (super.noSuchMethod(
            Invocation.method(#generateAccessToken, [userId, email]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#generateAccessToken, [userId, email]),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.method(#generateAccessToken, [userId, email]),
            ),
          )
          as String);

  @override
  String generateRefreshToken(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#generateRefreshToken, [userId]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#generateRefreshToken, [userId]),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.method(#generateRefreshToken, [userId]),
            ),
          )
          as String);

  @override
  String generateSensitiveAccessToken(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#generateSensitiveAccessToken, [userId]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#generateSensitiveAccessToken, [userId]),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.method(#generateSensitiveAccessToken, [userId]),
            ),
          )
          as String);

  @override
  _i6.JwtClaim? verifyToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#verifyToken, [token]),
            returnValueForMissingStub: null,
          )
          as _i6.JwtClaim?);

  @override
  String? getUserIdFromToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getUserIdFromToken, [token]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  String? getTokenType(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getTokenType, [token]),
            returnValueForMissingStub: null,
          )
          as String?);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i7.NotificationService {
  @override
  _i3.Future<Map<String, dynamic>> createInAppNotification({
    required String? userId,
    required String? type,
    required String? title,
    required String? body,
    String? spaceId,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createInAppNotification, [], {
              #userId: userId,
              #type: type,
              #title: title,
              #body: body,
              #spaceId: spaceId,
              #data: data,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> sendPushNotification({
    required String? userId,
    required String? title,
    required String? body,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendPushNotification, [], {
              #userId: userId,
              #title: title,
              #body: body,
              #data: data,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> sendEmail({
    required String? to,
    required String? subject,
    required String? htmlBody,
    String? textBody,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmail, [], {
              #to: to,
              #subject: subject,
              #htmlBody: htmlBody,
              #textBody: textBody,
            }),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> notify({
    required String? userId,
    required String? type,
    required String? title,
    required String? body,
    String? spaceId,
    Map<String, dynamic>? data,
    Set<_i7.NotificationChannel>? channels = const {
      _i7.NotificationChannel.inApp,
      _i7.NotificationChannel.push,
    },
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notify, [], {
              #userId: userId,
              #type: type,
              #title: title,
              #body: body,
              #spaceId: spaceId,
              #data: data,
              #channels: channels,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markRead(String? notificationId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markRead, [notificationId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markAllRead(String? userId, {String? spaceId}) =>
      (super.noSuchMethod(
            Invocation.method(#markAllRead, [userId], {#spaceId: spaceId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getPreferences(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPreferences, [userId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> registerDeviceToken({
    required String? userId,
    required String? token,
    required String? platform,
    String? deviceName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerDeviceToken, [], {
              #userId: userId,
              #token: token,
              #platform: platform,
              #deviceName: deviceName,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> unregisterDeviceToken({
    required String? userId,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unregisterDeviceToken, [], {
              #userId: userId,
              #token: token,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> updatePreferences(
    String? userId,
    Map<String, dynamic>? preferences,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreferences, [userId, preferences]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
