// Mocks generated by Mockito 5.4.6 from annotations
// in studio_pair_backend/test/calendar_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:studio_pair_backend/src/modules/calendar/calendar_repository.dart'
    as _i2;
import 'package:studio_pair_backend/src/modules/spaces/spaces_repository.dart'
    as _i4;
import 'package:studio_pair_backend/src/services/notification_service.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CalendarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarRepository extends _i1.Mock
    implements _i2.CalendarRepository {
  @override
  _i3.Future<Map<String, dynamic>> createEvent({
    required String? id,
    required String? spaceId,
    required String? createdBy,
    required String? title,
    String? location,
    required String? eventType,
    required bool? allDay,
    required DateTime? startAt,
    required DateTime? endAt,
    String? recurrenceRule,
    String? sourceModule,
    String? sourceEntityId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEvent, [], {
              #id: id,
              #spaceId: spaceId,
              #createdBy: createdBy,
              #title: title,
              #location: location,
              #eventType: eventType,
              #allDay: allDay,
              #startAt: startAt,
              #endAt: endAt,
              #recurrenceRule: recurrenceRule,
              #sourceModule: sourceModule,
              #sourceEntityId: sourceEntityId,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>?> getEventById(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getEventById, [eventId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getEventsByDateRange(
    String? spaceId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEventsByDateRange, [
              spaceId,
              startDate,
              endDate,
            ]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getEventsByDay(
    String? spaceId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEventsByDay, [spaceId, date]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> updateEvent(
    String? eventId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateEvent, [eventId, updates]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> softDeleteEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteEvent, [eventId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getUpcomingEvents(
    String? spaceId,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingEvents, [spaceId, limit]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getEventsForUser(
    String? userId,
    String? spaceId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEventsForUser, [
              userId,
              spaceId,
              startDate,
              endDate,
            ]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> countEventsInRange(
    String? spaceId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#countEventsInRange, [
              spaceId,
              startDate,
              endDate,
            ]),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<Map<String, dynamic>> createAlert({
    required String? id,
    required String? eventId,
    required int? minutesBefore,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAlert, [], {
              #id: id,
              #eventId: eventId,
              #minutesBefore: minutesBefore,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> deleteAlerts(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAlerts, [eventId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> createInvitation({
    required String? id,
    required String? eventId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createInvitation, [], {
              #id: id,
              #eventId: eventId,
              #userId: userId,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>?> updateInvitationStatus(
    String? eventId,
    String? userId,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateInvitationStatus, [
              eventId,
              userId,
              status,
            ]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getInvitationsForEvent(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getInvitationsForEvent, [eventId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> findInvitation(
    String? eventId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findInvitation, [eventId, userId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);
}

/// A class which mocks [SpacesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpacesRepository extends _i1.Mock implements _i4.SpacesRepository {
  @override
  _i3.Future<Map<String, dynamic>> createSpace({
    required String? id,
    required String? name,
    required String? type,
    String? description,
    String? iconUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSpace, [], {
              #id: id,
              #name: name,
              #type: type,
              #description: description,
              #iconUrl: iconUrl,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> listByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#listByUserId, [userId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> updateSpace(
    String? id, {
    String? name,
    String? description,
    String? iconUrl,
    String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateSpace,
              [id],
              {
                #name: name,
                #description: description,
                #iconUrl: iconUrl,
                #type: type,
              },
            ),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> softDeleteSpace(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteSpace, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> addMember({
    required String? spaceId,
    required String? userId,
    required String? role,
    required String? accessLevel,
    required String? status,
    String? invitedBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addMember, [], {
              #spaceId: spaceId,
              #userId: userId,
              #role: role,
              #accessLevel: accessLevel,
              #status: status,
              #invitedBy: invitedBy,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>?> getMember(
    String? spaceId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMember, [spaceId, userId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> listMembers(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#listMembers, [spaceId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> updateMember(
    String? spaceId,
    String? userId, {
    String? role,
    String? accessLevel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateMember,
              [spaceId, userId],
              {#role: role, #accessLevel: accessLevel},
            ),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> removeMember(String? spaceId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeMember, [spaceId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> leaveSpace(String? spaceId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveSpace, [spaceId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> transferOwnership(
    String? spaceId,
    String? fromUserId,
    String? toUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transferOwnership, [
              spaceId,
              fromUserId,
              toUserId,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> countActiveMembers(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#countActiveMembers, [spaceId]),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<Map<String, dynamic>?> findMembership(
    String? spaceId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findMembership, [spaceId, userId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>?> reactivateMember(
    String? spaceId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reactivateMember, [spaceId, userId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>> createInvite({
    required String? id,
    required String? spaceId,
    required String? code,
    required String? createdBy,
    int? maxUses,
    DateTime? expiresAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createInvite, [], {
              #id: id,
              #spaceId: spaceId,
              #code: code,
              #createdBy: createdBy,
              #maxUses: maxUses,
              #expiresAt: expiresAt,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>?> findInviteByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#findInviteByCode, [code]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> incrementInviteUses(String? inviteId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementInviteUses, [inviteId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> anonymizeUserContentInSpace(
    String? spaceId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#anonymizeUserContentInSpace, [spaceId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removePersonalReferencesInSpace(
    String? spaceId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removePersonalReferencesInSpace, [
              spaceId,
              userId,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deletePersonalDataInSpace(String? spaceId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePersonalDataInSpace, [spaceId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i5.NotificationService {
  @override
  _i3.Future<Map<String, dynamic>> createInAppNotification({
    required String? userId,
    required String? type,
    required String? title,
    required String? body,
    String? spaceId,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createInAppNotification, [], {
              #userId: userId,
              #type: type,
              #title: title,
              #body: body,
              #spaceId: spaceId,
              #data: data,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> sendPushNotification({
    required String? userId,
    required String? title,
    required String? body,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendPushNotification, [], {
              #userId: userId,
              #title: title,
              #body: body,
              #data: data,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> sendEmail({
    required String? to,
    required String? subject,
    required String? htmlBody,
    String? textBody,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmail, [], {
              #to: to,
              #subject: subject,
              #htmlBody: htmlBody,
              #textBody: textBody,
            }),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> notify({
    required String? userId,
    required String? type,
    required String? title,
    required String? body,
    String? spaceId,
    Map<String, dynamic>? data,
    Set<_i5.NotificationChannel>? channels = const {
      _i5.NotificationChannel.inApp,
      _i5.NotificationChannel.push,
    },
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notify, [], {
              #userId: userId,
              #type: type,
              #title: title,
              #body: body,
              #spaceId: spaceId,
              #data: data,
              #channels: channels,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markRead(String? notificationId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markRead, [notificationId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markAllRead(String? userId, {String? spaceId}) =>
      (super.noSuchMethod(
            Invocation.method(#markAllRead, [userId], {#spaceId: spaceId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getPreferences(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPreferences, [userId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> registerDeviceToken({
    required String? userId,
    required String? token,
    required String? platform,
    String? deviceName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerDeviceToken, [], {
              #userId: userId,
              #token: token,
              #platform: platform,
              #deviceName: deviceName,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> unregisterDeviceToken({
    required String? userId,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unregisterDeviceToken, [], {
              #userId: userId,
              #token: token,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> updatePreferences(
    String? userId,
    Map<String, dynamic>? preferences,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreferences, [userId, preferences]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
