// Mocks generated by Mockito 5.4.6 from annotations
// in studio_pair_backend/test/notifications_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:studio_pair_backend/src/modules/notifications/notifications_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NotificationsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationsRepository extends _i1.Mock
    implements _i2.NotificationsRepository {
  @override
  _i3.Future<List<Map<String, dynamic>>> listNotifications({
    required String? userId,
    String? cursor,
    int? limit = 25,
    bool? unreadOnly = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listNotifications, [], {
              #userId: userId,
              #cursor: cursor,
              #limit: limit,
              #unreadOnly: unreadOnly,
            }),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>> create({
    required String? id,
    required String? userId,
    required String? type,
    required String? title,
    required String? body,
    String? spaceId,
    String? sourceModule,
    String? sourceEntityId,
    String? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #id: id,
              #userId: userId,
              #type: type,
              #title: title,
              #body: body,
              #spaceId: spaceId,
              #sourceModule: sourceModule,
              #sourceEntityId: sourceEntityId,
              #data: data,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<bool> markRead(String? notificationId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markRead, [notificationId, userId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> markAllRead(String? userId, {String? spaceId}) =>
      (super.noSuchMethod(
            Invocation.method(#markAllRead, [userId], {#spaceId: spaceId}),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<Map<String, dynamic>?> getPreferences(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPreferences, [userId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>> upsertPreferences({
    required String? userId,
    required bool? pushEnabled,
    required bool? emailEnabled,
    required bool? quietHoursEnabled,
    required String? quietHoursStart,
    required String? quietHoursEnd,
    String? channelPreferences,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertPreferences, [], {
              #userId: userId,
              #pushEnabled: pushEnabled,
              #emailEnabled: emailEnabled,
              #quietHoursEnabled: quietHoursEnabled,
              #quietHoursStart: quietHoursStart,
              #quietHoursEnd: quietHoursEnd,
              #channelPreferences: channelPreferences,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
