// Mocks generated by Mockito 5.4.4 from annotations
// in studio_pair/test/activities_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:studio_pair/src/repositories/activities_repository.dart' as _i2;
import 'package:studio_pair/src/services/database/app_database.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ActivitiesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivitiesRepository extends _i1.Mock
    implements _i2.ActivitiesRepository {
  @override
  _i3.Future<List<_i4.CachedActivity>> getActivities(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getActivities, [spaceId]),
            returnValue: _i3.Future<List<_i4.CachedActivity>>.value(
              <_i4.CachedActivity>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.CachedActivity>>.value(
                  <_i4.CachedActivity>[],
                ),
          )
          as _i3.Future<List<_i4.CachedActivity>>);

  @override
  _i3.Future<Map<String, dynamic>> createActivity(
    String? spaceId, {
    required String? title,
    String? description,
    String? category,
    String? thumbnailUrl,
    String? trailerUrl,
    String? externalId,
    String? externalSource,
    String? privacy,
    String? mode,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createActivity,
              [spaceId],
              {
                #title: title,
                #description: description,
                #category: category,
                #thumbnailUrl: thumbnailUrl,
                #trailerUrl: trailerUrl,
                #externalId: externalId,
                #externalSource: externalSource,
                #privacy: privacy,
                #mode: mode,
                #metadata: metadata,
              },
            ),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getActivity(
    String? spaceId,
    String? activityId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getActivity, [spaceId, activityId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> updateActivity(
    String? spaceId,
    String? activityId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateActivity, [spaceId, activityId, data]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> deleteActivity(String? spaceId, String? activityId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteActivity, [spaceId, activityId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> restoreActivity(
    String? spaceId,
    String? activityId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#restoreActivity, [spaceId, activityId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> vote(
    String? spaceId,
    String? activityId,
    int? score,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#vote, [spaceId, activityId, score]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> removeVote(String? spaceId, String? activityId) =>
      (super.noSuchMethod(
            Invocation.method(#removeVote, [spaceId, activityId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getVotes(
    String? spaceId,
    String? activityId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getVotes, [spaceId, activityId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>> completeActivity(
    String? spaceId,
    String? activityId, {
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #completeActivity,
              [spaceId, activityId],
              {#notes: notes},
            ),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<_i4.CachedActivity>> searchActivities(
    String? spaceId,
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchActivities, [spaceId, query]),
            returnValue: _i3.Future<List<_i4.CachedActivity>>.value(
              <_i4.CachedActivity>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.CachedActivity>>.value(
                  <_i4.CachedActivity>[],
                ),
          )
          as _i3.Future<List<_i4.CachedActivity>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getCompletedActivities(
    String? spaceId, {
    String? cursor,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCompletedActivities,
              [spaceId],
              {#cursor: cursor, #limit: limit},
            ),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>> getStats(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getStats, [spaceId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getActivitiesByColumn(
    String? spaceId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getActivitiesByColumn, [spaceId, userId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Stream<List<_i4.CachedActivity>> watchActivities(String? spaceId) =>
      (super.noSuchMethod(
            Invocation.method(#watchActivities, [spaceId]),
            returnValue: _i3.Stream<List<_i4.CachedActivity>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<List<_i4.CachedActivity>>.empty(),
          )
          as _i3.Stream<List<_i4.CachedActivity>>);
}
